---
- hosts: jenkins
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/jenkins.yml
    - group_vars/VAULT
    - secret_group_vars/ssh_keys
    - host_vars/jenkins.yml
  pre_tasks:
    - name: Allow jenkins user to execute things as root
      copy:
        content: |
          jenkins ALL=(ALL:ALL) NOPASSWD:ALL
        dest: /etc/sudoers.d/jenkins
        validate: 'visudo -cf %s'
        mode: 0440
    - name: Run jenkins role 'configure default users' task
      template:
        src: roles/geerlingguy.jenkins/templates/basic-security.groovy.j2
        dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
        owner: "{{ jenkins_process_user }}"
        group: "{{ jenkins_process_group }}"
        mode: 0775
      register: jenkins_users_config
      when: jenkins_update_admin_password|d(False)
  roles:
    - common
    - geerlingguy.java
    - geerlingguy.jenkins
    - galaxyproject.nginx
  post_tasks:
    - name: Remove Jenkins security init scripts
      file:
        path: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
        state: absent
