approved_domains = {
  'UQ_users': [
    'awmc.uq.edu.au',
    'mater.uq.edu.au',
    'uq.connect.edu.au',
    'uq.edu.au',
    'uqconnect.net.au',
    'uq.net.edu',
    'uq.net',
    'imb.uq.edu.au',
    'uqconnect.edu',
    'uqconect.edu.au',
    'student.uq.edu.au',
    'student.uqconnect.edu.au',
    'uq.edu.eu',
    'uqconnect.edu.au',
    'uq.net.au',
    'uq.edu'
  ],
  'AdelaideU_users': [
    'adelaide.edu.au',
    'student.adelaide.edu.au',
  ],
  'RMIT_users': [
    'student.rmit.edu.au',
    'rmit.edu.au'
  ],
  'Monash_users': [
    'monash.edu.au',
    'student.monash.edu',
    'monash.edu',
  ],
  'UNSW_users': [
    'ad.unsw.edu.au',
    'unsw.edu.au',
    'student.unsw.edu.au',
    'unsw.edu.au ',
    'ccia.unsw.edu.au',
    'zmail.unsw.edu.au'
  ],
  'UoSydney_users': [
    'sydney.edu.au',
    'uni.sydney.edu.au'
  ],
  'Curtin_users': [
    'curtin.edu.au',
    'student.curtin.edu.au',
    'postgrad.curtin.edu.au',
    'graduate.curtin.edu.au'
  ],
  'UWA_users': [
    'student.uwa.du.au',
    'research.uwa.edu.au',
    'student.uwa.edu.au',
    'uwa.edu.au',
    'resphealth.uwa.edu.au'
  ],
  'CSIRO': [
    'csiro.au'
  ],
  'UoM_users': [
    'unimelb.edu.au',
    'student.unimelb.edu.au'
  ],
  'UTas_users': [
    'utas.edu.au'
  ],
  'QUT_users': [
    'edu.qut.au',
    'connect.qut.edu.au',
    'qut.connect.edu.au',
    'qut.edu.au',
    'qut.hdr.edu.au',
    'hdr.qut.edu.au',
  ],
  'GriffithU_users': [
    'griffithuni.edu.au',
    'griffith.edu.au'
  ],
  'JCU_users': [
    'my.jcu.edu.au',
    'jcu.edu.au'
  ],
  'UTS_users': [
    'uts.edu.au',
    'student.uts.edu.au',
  ],
  'USQ_users': [
    'usq.edu.au',
    'umail.usq.edu.au'
  ],
  'Australian_researchers_mix': [
    'petermac.org',
    'une.edu.au',
    'svi.edu.au',
    'inaburrastudents.nsw.edu.au',
    'uon.edu.au',
    'mcri.edu.au',
    'vcgs.org.au',
    'mq.edu.au',
    'mater.org.au',
    'bond.edu.au',
    'qimr.edu.au',
    'biocommons.org.au',
    'svha.org.au',
    'aapoly.edu.au',
    'student.westernsydney.edu.au',
    'newcastle.edu.au',
    'hudson.org.au',
    'CDU.EDU.AU',
    'sahmri.com',
    'ccg.murdoch.edu.au',
    'murdoch.edu.au',
    'sims.org.au',
    'centenary.org.au',
    'mh.org.au',
    'student.edu.au',
    'students.mq.edu.au',
    'federation.edu.au',
    'usc.edu.au',
    'anu.edu.au',
    'westernsydney.edu.au',
    'cqu.edu.au',
    'deakin.edu.au',
    'student.usc.edu.au',
    'qfab.org',
    'uow.edu.au',
    'aarnet.edu.au',
    'qimrberghofer.edu.au',
    'calvarymater.org.au',
    'scu.edu.au',
    'pawsey.org.au',
    'hdr.mq.edu.au',
    'ecu.edu.au',
    'research.usc.edu.au',
    'parrastu.catholic.edu.au',
    'unisa.edu.au',
    'student.murdoch.edu.au',
    'redcrossblood.org.au',
    'menzies.edu.au',
    'mymail.unisa.edu.au',
    'vidrl.org.au',
    'students.latrobe.edu.au',
    'flinders.edu.au',
    'latrobe.edu.au',
    'student.swin.edu.au',
    'telethonkids.org.au',
    'wehi.edu.au',
    'cdu.edu.au',
    'csu.edu.au',
    'student.scu.edu.au',
    'smu.org.au',
    'student.kings.edu.au',
    'gebri.usc.edu.eg',
    'florey.edu.au',
    'ccia.org.au',
    'bioplatforms.com',
    'bakeridi.edu.au',
    'agrf.org.au',
    'onjcri.org.au',
    'swin.edu.au',
    'garvan.org.au',
    'qcif.edu.au',
    'cmri.org.au'
  ],
  'Australian_other': [
    'sugarresearch.com.au',
    'microbelabs.com.au',
    'snp.com.au',
    'inaburrastudents.nsw.edu.au',
    'genea.com.au',
    'lonsbio.com.au',
    'crocresearch.com.au',
    'rcpaqap.com.au',
    'bioproperties.com.au',
    'uniquest.com.au',
    'bri.sonichealth.com.au',
    'tasalk.com.au',
    'baulkhamhillshighschool.com.au'
  ],
  'Australian_government': [
    'dbca.wa.gov.au',
    'act.gov.au',
    'qm.qld.gov.au',
    'foodstandards.gov.au',
    'health.wa.gov.au',
    'ecodev.vic.gov.au',
    'dpi.nsw.gov.au',
    'ths.tas.gov.au',
    'defence.gov.au',
    'health.nsw.gov.au',
    'sa.gov.au',
    'daf.qld.gov.au',
    'austmus.gov.au',
    'agriculture.gov.au',
    'health.qld.gov.au',
    'hnehealth.nsw.gov.au',
    'education.nsw.gov.au',
    'rbg.vic.gov.au',
    'des.qld.gov.au',
    'environment.gov.au',
    'agriculture.vic.gov.au',
    'health.gov.au',
    'aims.gov.au'
  ]
}
