import os

from dotenv import load_dotenv

load_dotenv()

STAGING_GALAXY_API_KEY = os.environ['STAGING_GALAXY_API_KEY']
STAGING_GALAXY_BASEURL = os.environ['STAGING_GALAXY_BASEURL']
PROD_GALAXY_API_KEY = os.environ['PROD_GALAXY_API_KEY']
PROD_GALAXY_BASEURL = os.environ['PROD_GALAXY_BASEURL']

GALAXY_USER_EP = "users"
GALAXY_GROUP_EP = "groups/"
GALAXY_GROUP_USER_EP = "/users"

SLACK_TOKEN = os.environ['SLACK_TOKEN']
SLACK_ALERT_CHANNEL = os.environ['SLACK_ALERT_CHANNEL']
SLACK_LOG_CHANNEL = os.environ['SLACK_LOG_CHANNEL']
SLACK_ALERT_MENTIONS = os.environ['SLACK_ALERT_MENTIONS']
SLACK_LOG_MENTIONS = os.environ['SLACK_LOG_MENTIONS']
