---
- name: Create workflow invocations directory
  ansible.builtin.file:
    path: "{{ workflow_invocations_dir }}"
    state: directory
    owner: ubuntu

- name: Template workflow invocations .env file
  ansible.builtin.template:
    src: workflows_reporting/env.j2
    dest: "{{ workflow_invocations_dir }}/.env"
    mode: "0600"
    owner: ubuntu

- name: Template workflow invocations Python script
  ansible.builtin.template:
    src: workflows_reporting/collect_workflow_invocations.py.j2
    dest: "{{ workflow_invocations_dir }}/collect_workflow_invocations.py"
    mode: "0755"
    owner: ubuntu

- name: Add cron job to run workflow invocations collection script
  ansible.builtin.cron:
    name: "Collect workflow invocations every quarter hour"
    minute: "*/15"
    hour: "*"
    job: >-
      cd {{ workflow_invocations_dir }}
      && {{ virtualenv_dir }}/bin/python collect_workflow_invocations.py
      {{ nginx_workflows_log }}
      >> workflow_invocations.log 2>&1
    when: workflows_reporting_enabled
