---
- name: Create workflow invocations directory
  ansible.builtin.file:
    path: "{{ workflow_invocations_dir }}"
    state: directory
    owner: ubuntu

- name: Template workflow invocations .env file
  ansible.builtin.template:
    src: workflows_reporting/env.j2
    dest: "{{ workflow_invocations_dir }}/.env"
    mode: "0600"
    owner: ubuntu

- name: Template workflow invocations Python script
  ansible.builtin.template:
    src: workflows_reporting/collect_workflow_invocations.py.j2
    dest: "{{ workflow_invocations_dir }}/collect_workflow_invocations.py"
    mode: "0755"
    owner: ubuntu
