telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["{{ grafana_server_url }}"]
      - database = "ancillary"
      - precision = "s"
      - username = "node"
      - password = "{{ vault_influx_node_password }}"

s3_bucket: "{{ vector_s3_bucket }}"
s3_endpoint: "{{ vector_s3_endpoint }}"
s3_access_key_id: "{{ vector_s3_access_key_id }}"
s3_secret_access_key: "{{ vector_s3_secret_access_key }}"
s3_key_prefix: galaxy/nginx-logs/
