---
- name: Create reporting dir
  ansible.builtin.file:
    path: "{{ reporting_dir }}"
    state: directory
    owner: "{{ reporting_user }}"
    mode: "0755"

- name: Clone reporting-service repo
  ansible.builtin.git:
    repo: "{{ reporting_service_repo_url }}"
    dest: "{{ reporting_repo }}"
    version: "{{ reporting_service_version }}"
    force: true
  become: true
  become_user: "{{ reporting_user }}"

- name: Create logs dir
  ansible.builtin.file:
    path: "{{ logs_dir }}"
    state: directory
    owner: "{{ reporting_user }}"
    mode: "0755"

- name: Install logrotate config for reporting-service logs
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/reporting-service
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Create virtualenv
  pip:
    virtualenv: "{{ virtualenv_dir }}"
    requirements: "{{ reporting_repo }}/requirements.txt"

- name: Template reporting-service .env file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ reporting_repo }}/.env"
    mode: "0600"
    owner: "{{ reporting_user }}"

- name: Template S3 retention policy
  ansible.builtin.template:
    src: s3-retention-policy.json.j2
    dest: "{{ reporting_repo }}/retention-policy.json"
    mode: "0644"
    owner: "{{ reporting_user }}"

- name: Add cron job to run S3 log cleanup daily
  ansible.builtin.cron:
    name: "S3 log data retention cleanup"
    user: "{{ reporting_user }}"
    minute: "0"
    hour: "2"
    job: >-
      {{ virtualenv_dir }}/bin/python
      {{ reporting_repo }}/s3_cleanup.py
      --policy '{{ reporting_repo }}/retention-policy.json'
      >> {{ logs_dir }}/s3_cleanup.log 2>&1

- name: Include workflows reporting tasks
  include_tasks: workflows.yml

- name: Include tools reporting tasks
  include_tasks: tools.yml
