---
- name: Add cron job to run tool runs collection script
  ansible.builtin.cron:
    name: "Collect tool runs every quarter hour"
    user: "{{ reporting_user }}"
    minute: "*/15"
    hour: "*"
    job: >-
      flock -n {{ reporting_dir }}/tool_runs.lock
      {{ virtualenv_dir }}/bin/python
      {{ reporting_repo }}/report.py tools
      >> {{ logs_dir }}/tool_runs.log 2>&1
  when: "'tools' in enabled_reporting_services"
